apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress
      ports:
        - wordpress-port: 80
      envFrom:
        - secretRef:
            name: wordpress-secret
        - configMapRef:
            name: wordpress-configmap
      volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mariavolume
  nodeSelector:
    type: db
  volumes:
    - name: mariavolume
      persistentVolumeClaim:
        claimName: mariaclaim