apiVersion: v1
kind: Pod
metadata:
  generateName: wordpress-
  labels:
    name: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress
      ports:                              
        - containerPort: 80
          protocol: TCP
      envFrom:
        - secretRef:
            name: wordpress-secret
        - configMapRef:
            name: wordpress-configmap